version: "3.8"
services:
  web:
    build:
      context: .
    container_name: banking_api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    volumes:
      - ./:/app
  mysql:
    image: mysql:5.7
    container_name: banking_mysql
    restart: always
    command: mysqld --user=root --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      timeout: 5s
      retries: 10
